# version: '3.7'

services:
  django_gunicorn:
    container_name: backend
    volumes:
      - static:/static
    env_file:
      - ./Backend/.env
    build:
      context: ./Backend
    ports: # TODO: DEBUG only; remove
      - "8000:8000"
    networks: 
      - dev
  nginx:
    restart: always
    container_name: nginx
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
      - react_app
    networks:
      - dev
  react_app:
    container_name: frontend
    build:
      context: ./Frontend
    environment:
      - NODE_ENV=production
    ports: # TODO: DEBUG only; remove
      - "3000:3000"
    networks:
      - dev
  db:
    container_name: database # or maybe "db"?
    build:
      context: ./Database
    volumes:
      - ./Database/database:/var/lib/postgresql/data
    restart: always
    networks:
      - dev

volumes:
  static:

networks:
  dev:
    driver: bridge
