# version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - ./Backend/.env
    build:
      context: ./Backend/src
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
  react_app:
    build:
      context: ./Frontend
    container_name: docker-next
    ports:
      - "3000:3000"
    volumes:
      - static:/static
      - /app/node_modules
  db:
    build:
      context: ./dockerfile 
    container_name: p-c
    environment:
      POSTGRES_USER: paint_user
      POSTGRES_PASSWORD: paint
      POSTGRES_DB: PAINT_database
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    restart: always

volumes:
  static:
