# version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - ./Backend/.env
    build:
      context: ./Backend/src
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
  react_app:
    build:
      context: ./Frontend
    container_name: docker-next
    ports:
      - "3000:3000"
    volumes:
      - static:/static
      - /app/node_modules

volumes:
  static:
