# version: '3.7'

services:
  django_gunicorn:
    container_name: backend
    volumes:
      - static:/static
    env_file:
      - ./Backend/.env
    build:
      context: ./Backend
    networks: 
      - dev
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
    networks:
      - dev
  react_app:
    container_name: frontend
    build:
      context: ./Frontend
    volumes:
      - static:/static
      - /app/node_modules
    networks:
      - dev
  db:
    container_name: database # or maybe "db"?
    build:
      context: ./Database
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always
    networks:
      - dev

volumes:
  static:

networks:
  dev:
    driver: bridge
